print('assignment operators (like sending an operation to a value) include:')
print('/n= assignment of a variable\n x=3')
print('\n+= addition of a value to a variable\nx=3\nx+=1 => 4')
print('\n-= subtraction of a value from a variable\nx=3\nx-=1 =>2')
print('\n*= multiplication of a value against a variable\nx=3\nx*=2 =>6')
print('\n/= division of a variable by a value\nx=3\nx/=2 =>1.5')
print('\n//= double division of a variable by a value\nreturns the floor value for both integer and floating-point arguments after division\nx=3\nx//=2 =>1')
print('\n%= modulus of a variable by a value\nreturns the remainder\nx=3\nx%=2 => 1')
print('\n**= exponential operation on a variable to a value\nx=3\nx**=2 =>9')
