print('common error types')
print('\nSyntax - you wrote it wrong')
print('\nIndentation - you indented or forgot to indent something')
print('\nType - you used or returned the wrong type')
print('\nName - you didnt define a variable')
print('\nZero Division - you divided by 0')
print('\nIndex - you miscalculated your index')
print('\nRuntime - you fucked up')
print('\nAttribute - you tried to use a method that isnt part of that class')

print('\nHandling errors')
